steps:
  - label: ":golang: build"
    key: build
    commands:
      - "GOOS=darwin GOARCH=arm64 go build -o ./hello/hello ./hello"
    artifact_paths: "./hello/hello"
    plugins: 
      - docker#v5.13.0:
          image: golang:1.25.5

  - label: block
    key: block
    block: "Block Step"
    prompt: "Enter your name"
    fields:
      - text: "name"
        key: "name"
    depends_on: ["build"]

  - label: run
    command:
      - buildkite-agent artifact download "hello/hello" .
      - chmod +x ./hello/hello
      - ls -al ./hello/hello
      - ./hello/hello $(buildkite-agent meta-data get "name")
    depends_on:
      - block